#!/usr/bin/python
# -*- coding: utf-8 -*-
# Exercise number 02 from https://projecteuler.net/archives
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

__author__ = 'SLP'
from time import time
class Fibonacci():
    def __init__(self,limitup):
        """
        Init method
        :param limitup: Upper limit to calculate de Fibonacci sequence

        """
        self.__limitup = limitup
        self.__sequence = []
        self.__suma = 0
        self.__startTime = time()

    def fibonaci(self, n):
        """
        Fibonaci method, return de n possition of de sequence.
        :param n: Position of sequence desired.
        :return Number of position given
        :ejem:
        if fibonaci sequence is: 0,1,1,2,3,5,...
        0 = fibonaci(0)
        1 = fibonaci(1)
        1 = fibonaci(2)
        2 = fibonaci(3)
        3 = fibonaci(4)
        5 = fibonaci(5)
        ...

        """
        if n == 0:
            return 0
        if n == 1:
            return 1
        return(self.fibonaci(n-1) + self.fibonaci(n-2))

    def calculateSequence(self, limitup=None):
        if limitup is None:
            limitup = self.__limitup

        j = self.fibonaci(0)
        i = 0
        while (j < limitup):
            j = self.fibonaci(i)
            self.__sequence.append(j)
            i += 1

    def calculateEven(self):
        for number in self.__sequence:
            if not number%2:
                self.__suma += number

    def getSequence(self):
        return self.__sequence

    def getSumma(self):
        return self.__suma

    def main(self):
        self.calculateSequence()
        self.calculateEven()
        #print(self.getSumma())
        print('Elapsed time: {}'.format(time()-self.__startTime))

if __name__ == '__main__':
    exc2 = Fibonacci(4000000)
    exc2.main()
